name: Django CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codes
        uses: actions/checkout@v2

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.9

      - name: Install pipenv
        run: |
          pip install pipenv

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

#          echo "${HOME}/.poetry/bin" >> $GITHUB_PATH

#      - name: Install Poetry
#        run: |
#          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
#          echo "${HOME}/.poetry/bin" >> $GITHUB_PATH

#      - name: Install dependencies
#        run: |
#          ${HOME}/.poetry/bin/poetry install

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Test python project
        run: |
          pipenv run python manage.py test